/* Correctly-rounded atan2 function for two binary64 values.

Copyright (c) 2024-2025 Paul Zimmermann and Alexei Sibidanov

The original version of this file was copied from the CORE-MATH
project (file src/binary64/atan2/atan2.c, revision 8ea8ea35).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/* This implementation was possible with the help of Silviu-Ioan Filip,
   who designed the code to generate a rational approximation of atan(z)
   over (0,1). See comments before P[] and Q[] below. */

#include <fenv.h>
#include <stdint.h>
#include <math.h>
#include <libm-alias-finite.h>
#include "math_config.h"

#include "atan2_tint.h"
#include "e_atan2_data.h"

/* On targets without floating-point exception support (e.g. soft-float)
   the FE_* macros are not defined.  The accurate path only uses them to
   manage the exception flags, which do not exist there, so treat them as
   no-ops: fetestexcept (0) returns 0 and feclearexcept (0) does nothing.  */
#ifndef FE_INEXACT
#  define FE_INEXACT 0
#endif
#ifndef FE_UNDERFLOW
#  define FE_UNDERFLOW 0
#endif
#ifndef FE_OVERFLOW
#  define FE_OVERFLOW 0
#endif

#define MASK UINT64_C (0x7fffffffffffffff) // 2^63-1 (mask the sign bit)

// PI_H+PI_L approximates pi with error bounded by 2^-108.041
#define PI_H 0x1.921fb54442d18p+1
#define PI_L 0x1.1a62633145c07p-53
// PI_OVER2_H+PI_OVER2_L approximates pi/2 with error bounded by 2^-109.041
#define PI_OVER2_H 0x1.921fb54442d18p+0
#define PI_OVER2_L 0x1.1a62633145c07p-54
// PI_OVER4_H+PI_OVER4_L approximates pi/4 with error bounded by 2^-110.041
#define PI_OVER4_H 0x1.921fb54442d18p-1
#define PI_OVER4_L 0x1.1a62633145c07p-55

/* The following polynomials z*P(z) and Q(z) are a rational approximation
   of atan(z) on [0,1] generated by the test_atan program from
   rminimax (revision 94902ef):
   The relative approximation error output by rminimax is:
   fpminimax error = 3.99613e-59 (this is the relative error for P(x)/Q(x)
   with respect to atan(x)/x, which equals the relative error for x*P(x)/Q(x)
   with respect to atan(x)).
   The content of the output file atan_fpminimax.sollya is the following
   (Numerator is P(x), and Denominator is Q(x)):
Numerator = [|
0x2.09c0fe2d4c44bb29c73989e7519ea91406726ca119adbfp-12,
0xb.3cf74b427d53e03ee590b839e751890f2570b12bcb2381ap-12,
0x2.c21262c5ee230e68478de0875e1363e89e56c52e12e75e3p-8,
0x7.ea5d53dda9586c1d92a12df585026e1c90046cfd9a5b47f8p-8,
0x1.2ca8329170bf670dc1702b59c84b50b37d942f8d3769ef4p-4,
0x2.5aaa9752ebff1643c8f6de0edb933954b15381534eda7df8p-4,
0x4.1e6a0dafd431588d6c7ceb71f5cec19a77a386c00fd01e5p-4,
0x6.5de3ba90cbe60835e3367d9f6f7d371ab4597cf27f5c488p-4,
0x8.cf8f7c585767042cd92a5b9ac13d8c8043bd4a023dbe04dp-4,
0xa.fdc36d6b36139bf11df63474e3859d442b30b2c089a2b6cp-4,
0xc.6f8fb14638225192f9f04cf55c103771c44675c6d483606p-4,
0xc.ce79f10f754e31591ce47edcbc8a4eeb2a6f721ac656b42p-4,
0xc.090384dbd77132e1dfb4d9a1d595de7e506ca899a394f7p-4,
0xa.556ac9eee25e867d84dafa25141d203f1c7c2a5156b3ec3p-4,
0x8.1bd2677ddfcbc381df33f27dbb60939cb4c2c73286a6c29p-4,
0x5.cf6890b4eb9746ce40ecaee7789e113cba5cabcb5c9e199p-4,
0x3.cb7db6a1d6d99beb0a774e9a709d31960ee49825db23c314p-4,
0x2.40b4d3536e443b61bcfb377f5abc2a7e3a5435f9c2a3a6c8p-4,
0x1.35df4832c39c240f59a062ecccea6ea27d5e854a7f98ca68p-4,
0x9.5db9977c5e6e26385367a63fab8a720fc2b63bd115998d8p-8,
0x4.0be5b6c11b6afa6b863c0af94484ecd862a74b8aae890acp-8,
0x1.8bdd8845186a4130f13cad7c3bdd36cf744b7b5025259982p-8,
0x8.40c38ccfcb5dc64b55a44095bf7f3126668b8792d4ecd08p-12,
0x2.5c1d2bdeca1ac67b082ab087cc4c3c74da7a7f6f75214a28p-12,
0x9.054011c32d4b7a5c68d3c5d525f4af4eeb3c98615dee188p-16,
0x1.bbb6945d5565762aea6ec351e1d3551a7e40c419a7c0eb76p-16,
0x4.077cd0d9f2cd5f28c7357f0328fefa4e8e0194f353816ce8p-20,
0x6.50b6ea4e69842a65d6c651bca00813e0fe3fa3cc2a4378bp-24,
0x5.05d00dc3a15d400f36e0a54a8b6bf820fa981ec3c482e978p-28,
-0x1.38088112d9cca2b819e68e1f4fe2158753b900d05822353ap-60|];
Denominator = [|
0x2.09c0fe2d4c44bb29c73989e7519ea91406726ca119adbfp-12,
0xb.3cf74b427d53e03ee590b839e751890f2570b12bcb238cfp-12,
0x2.ccf112bc350f27a3d109be11851c076e5e7927716e161108p-8,
0x8.264d256f0bf4d61ee21431cc0f29764ce0cc1b593ac9952p-8,
0x1.3b2f8928ed0f65ddde810f893bbca452e8578dc057f6dbfp-4,
0x2.83e22371eaae527bd88fc66b104f6c8e151d128593dc3b34p-4,
0x4.7ece38b955841470d4fb97d6d7e1efdd7cb50c07514b8bcp-4,
0x7.1c0b45bc528f70ab02523c0ae4048f5cfd5521189747598p-4,
0xa.164ccdbb65ee133e623433c5e086402cb228afd335a245fp-4,
0xc.ed0c0cbe44fac2fd7c2adfc7c5dda9ea22b4a311cf5a5b1p-4,
0xf.0e6660438c903713dca1a0f58f0d9438a92b9de68c4488cp-4,
0x1p+0,
0xf.8ea68f9ad849103b257e4bfc606967f818fa2816928c4aap-4,
0xd.dc64eeee350623447a33ea40a2b22e4a6a2c129ace2470ap-4,
0xb.52ddfba2d37c8e224551a9b19fa064a3d78c68b54bc385p-4,
0x8.7ac113d26b683a14e97756c38785b0bf75f0a4506931ba8p-4,
0x5.d0328385c8079eaf24ec7cf91c78f75b402ea46b3f8ee6c8p-4,
0x3.a40b4a92ff0891065173f9b20e96e0a1467aed15fe33328p-4,
0x2.1390172457ddda6c3eabcd30f14774e6a5fe82ba64e0b24cp-4,
0x1.12db48d8fcd9d767c15f816db67b77ea0c399fedcf1dffe8p-4,
0x8.01a0c1a0dfefc92f8e0a97902e08d4781898e0b7d8ef0bcp-8,
0x3.56742224c37c1f6ea32c00086127eebfe033246a82f77e24p-8,
0x1.3b6ad4d3096ee4639ef840e9c09012b2662dd954d548c09cp-8,
0x6.5ba286ceb1697344bc3da132cbbe8025d30ae77005420eb8p-12,
0x1.c254a5c056c9647d2f92273519dae2d8e142ed5a56be2da4p-12,
0x6.82bdb6848076986af025d8bf5c3cd2f11f689adb05f5038p-16,
0x1.363e39445fdef5ca334d0fe1480e7ddc0b5399791828af16p-16,
0x2.bae9c43c14eab0ecc3a975bec45bddd62a6f3fbd5a63e3c4p-20,
0x4.25cd6d03b66803e89f2a803039fbb58a67a12ccb411479fp-24,
0x3.3292e4119e1a4df48cf079a47049f07fd24f82de8f791668p-28|];
*/

// use a type [29,29] rational approximation of atan(z) for 0 <= z <= 1
static double __attribute__ ((noinline))
atan2_accurate (double y, double x)
{
  fenv_t env;
  __feholdexcept (&env);
  int underflow;
  int overflow = __fetestexcept (FE_OVERFLOW);
  double res;
  /* First check when t=y/x is small and exact and x > 0, since for
     |t| <= 0x1.d12ed0af1a27fp-27, atan(t) rounds to t (to nearest). */
  double t = y / x;

  /* If t = y/x did underflow for x > 0, then atan(y/x) will underflow
     too, since the Taylor expansion of atan(z) is z - z^3/3 + o(z^3).
     If |t| < 2^-1022 and is exact, then atan(y/x) underflows, and also
     when |t| = 2^-1022, is exact, and rounding is toward zero. */
  int inexact = __fetestexcept (FE_INEXACT);
  double u = copysign (1.0, y);
  double v = fma (u, -0x1p-54, u);
  // when rounding toward zero, v != u, otherwise v = u
  underflow = x > 0
	      && (__fetestexcept (FE_UNDERFLOW)
		  || (!inexact
		      && (fabs (t) < 0x1p-1022
			  || (fabs (t) <= 0x1p-1022 && v != u))));

  /* If t is exact and underflows, then atan(y/x) rounds to t for x > 0,
     to pi for y > 0 and x < 0, and to -pi for x, y < 0. */
  if (t == 0)
    {
      if (x > 0)
	{
	  __feupdateenv (&env);
	  return t;
	}
      res = (y > 0) ? PI_H + PI_L : -PI_H - PI_L;
      goto end;
    }
  double corr = fma (t, x, -y);
  if (corr == 0 && x > 0) // t is exact
    if (fabs (t) <= 0x1.d12ed0af1a27fp-27)
      {
	// Warning: if y is in the subnormal range, t might differ from y/x
	/* If |y| >= 2^-969, then since t*x has at most 106 significant bits,
	   and t*x ~ y, the lower bit of t*x is >= 2^-1074, thus there is no
	   underflow in t*x-y. */
	if (fabs (y) >= 0x1p-915)
	  {
	    __feupdateenv (&env);
	    return fma (t, -0x1p-54, t);
	  }
	/* Now |y| < 2^-969, since x >= 2^-1074, then t <= 2^105, thus we can
	   scale y and t by 2^105, which will ensure t*x-y does not underflow.
	 */
	corr = fma (t * 0x1p105, x, -y * 0x1p105);
	if (corr == 0)
	  {
	    res = fma (t, -0x1p-54, t);
	    __feupdateenv (&env);
	    return res;
	  }
      }

  int inv = fabs (y) > fabs (x);
  tint_t z[1], p[1], q[1];
  if (inv)
    div_tint_d (z, x, y);
  else
    div_tint_d (z, y, x);

  /* When |y/x| < 2^-27, x > 0, atan(y/x) rounds to the same value as y/x
     pertubed by a small amount towards zero (here we subtract 2 to z->l).
     But since the Taylor expansion of atan(t) is t - t^3/3 + O(t^5),
     we have a relative error bounded by t^2/2 for t small enough.
     We thus need |y/x| < 2^-96 so that this error is less than 1 ulp. */
  if (inv == 0 && x > 0 && z->ex <= -96)
    {
      z->l -= 2;
      z->m -= (z->l < 2);
      z->h -= (z->m < 1);
      res = tint_tod (z, 1, y, x);
      goto end;
    }

  // below when we write y/x it should be read x/y when |x/y| < 1
  // |z - y/x| < 2^-185.53 * |z| (relative error from div_tint_d)
  // the rational approximation is only for z > 0, it is not antisymmetric
  int sz = z->sgn;
  z->sgn = 0;
  cp_tint (p, P + 29);
  cp_tint (q, Q + 29);
  for (int i = 28; i >= 0; i--)
    {
      mul_tint (p, p, z);
      mul_tint (q, q, z);
      add_tint (p, p, P + i);
      add_tint (q, q, Q + i);
    }
  // multiply p by z
  mul_tint (p, p, z);
  /* The routine errPsplit(e,13) in atan2.sage gives a relative error bound
     of 2^-184.14 for |p - z*P(z)|, for -11 <= e <= 0, which corresponds
     to 2^-12 <= z <= 1. */
  /* The routine errQsplit(e,12) in atan2.sage gives a relative error bound
     of 2^-184.19 for |q - Q(z)|, for -11 <= e <= 0, which corresponds
     to 2^-12 <= z <= 1. */
  // divide p by q
  div_tint (z, p, q);
  /* The relative error of div_tint() is <= 2^-185.53, thus we have:
     z*P(z)/Q(z) = atan(z) * (1 + eps0) with |eps0| < 3.99613e-59
     z = y/x * (1 + eps1) with |eps1| < 2^-185.53
     p = z*P(z) * (1 + eps2) with |eps2| < 2^-184.14
     q = Q(z) * (1 + eps3)   with |eps3| < 2^-184.19
     newz = p/q * (1 + eps4) with |eps4| < 2^-185.53
     The equality z = y/x * (1 + eps1) gives
     atan(z) = atan(y/x) + eps1*y/x * 1/(1+theta^2) for theta in (z,y/x).
     Thus |atan(z) - atan(y/x)| <= |eps1*y/x| which yields
     |atan(z) - atan(y/x)|/|atan(y/x)| <= |eps1*y/x|/|atan(y/x)|
     Since t/atan(t) is bounded by 1/atan(1) for 0 <= x <= 1, this yields:
     atan(z) = atan(y/x) * (1 + eps5) with |eps5| <= eps1/atan(1) < 2^-185.18.
     In summary we have:
     newz = atan(y/x)*(1+eps0)*(1+eps2)*(1+eps4)*(1+eps5)/(1+eps3)
     thus:
     newz = atan(y/x)*(1+eps6) with |eps6| < 2^-182.63.
     This corresponds to a maximal error of 2^-182.63*2^192 <= 662 ulps.
  */
  uint64_t err = 662; // error bound in case inv=0 and x > 0
  z->sgn = sz;	      // restore sign
  /* Now z approximates atan(y/x) for inv=0, and atan(x/y) for inv=1,
     with -pi/4 < z < pi/4.
  */
  if (inv)
    {
      // if x/y > 0 thus atan(x/y) > 0 we apply pi/2 - atan(x/y)
      // if x/y < 0 thus atan(x/y) < 0 we apply -pi/2 - atan(x/y)
      if (z->sgn == 0)
	{ // 0 < atan(x/y) < pi/4
	  z->sgn = 1;
	  add_tint (z, &PI2, z);
	  /* Now pi/4 < z < pi/2. The absolute error on z was bounded by
	     2^-182.63*pi/4, the error on PI2 is bounded by 2^-197.96, and
	     the add_tint() error is bounded by 2 ulp(pi/2) = 2^-190,
	     which yields a total error < 2^-182.63*pi/4 + 2^-197.96 + 2^-190
	     < 2^-182.967. Relatively to ulp(pi/4) this is less than 524. */
	}
      else // -pi/4 < atan(x/y) < 0
	{
	  add_tint (z, &PI2, z);
	  z->sgn = 1;
	  /* Now -pi/2 < z < -pi/4. The same error analysis as above applies,
	     thus we get the same bound of 524 ulps. */
	}
      err = 524;
    }
  // now -pi/2 < z < pi/2
  // if x is negative we go to the opposite quadrant
  if (x < 0)
    {
      if (z->sgn == 0)
	{ // 1st quadrant -> 3rd quadrant (subtract pi)
	  z->sgn = 1;
	  add_tint (z, &PI, z);
	  z->sgn = 1;
	  /* We had 0 < z < pi/2 thus now -pi < z < -pi/2.
	     The absolute error on z was bounded by
	     max(2^-182.63*pi/4,2^-182.967) = 2^-182.967, that on PI is bounded
	     by 2^-196.96, and the add_tint() error is bounded by 2 ulp(pi) =
	     2^-189, which yields a total error < 2^-182.967 + 2^-196.96 +
	     2^-189 < 2^-182.945. Relatively to ulp(pi/2) this is less than 266
	     ulps. */
	}
      else // 4th quadrant -> 2nd quadrant (add pi)
	{
	  add_tint (z, &PI, z);
	  /* If inv=0 we had -pi/4 < z < 0 thus now 3pi/4 < z < pi.
	     If inv=1 we had -pi/2 < z < -pi/4 thus now pi/2 < z < 3pi/4.
	     The same analysis as above applies, and we get the same bound
	     of 266 ulps. */
	}
      err = 266;
    }
  res = tint_tod (z, err, y, x);
end:
  if (!overflow)
    __feclearexcept (FE_OVERFLOW);
  if (!underflow)
    __feclearexcept (FE_UNDERFLOW);
  __feupdateenv (&env);
  return res;
}

static inline double
fasttwosum (double x, double y, double *e)
{
  double s = x + y, z = s - x;
  *e = y - z;
  return s;
}

static inline double
fastsum (double xh, double xl, double yh, double yl, double *e)
{
  double sl, sh = fasttwosum (xh, yh, &sl);
  *e = (xl + yl) + sl;
  return sh;
}

static double __attribute__ ((noinline))
as_atan2_special (double y0, double x0)
{
  uint64_t iy = asuint64 (y0), ix = asuint64 (x0);
  uint64_t aiy = iy << 1, aix = ix << 1;

  if (__glibc_unlikely (aiy >= UINT64_C (0x7ff) << 53
			|| aix >= UINT64_C (0x7ff) << 53))
    { // NaN or Inf
      if (aiy > UINT64_C (0x7ff) << 53 || aix > UINT64_C (0x7ff) << 53)
	// return y0 + x0; // if y or x is sNaN, returns qNaN and raises
	// invalid
	return y0 + x0;
      // Now neither y nor x is NaN, but at least one is +Inf or -Inf
      if (aiy == UINT64_C (0x7ff) << 53 && aix == UINT64_C (0x7ff) << 53)
	{ // both y and x are +/-Inf
	  static const double finf[][2]
	      = { { 0x1p-55, 0x1.921fb54442d18p-1 },
		  { 0x1p-54, 0x1.2d97c7f3321d2p+1 } };
	  // atan2 (+/-Inf,-Inf) = +/-3pi/4
	  // atan2 (+/-Inf,+Inf) = +/-pi/4
	  return copysign (finf[ix >> 63][1], y0)
		 + copysign (finf[ix >> 63][0], y0);
	}
      // now only one of y and x is +/-Inf
      if (aix == UINT64_C (0x7ff) << 53)
	{
	  if (x0 < 0)
	    return copysign (PI_H, y0) + copysign (PI_L, y0);
	  // atan2(+/-0,x) = +/-0 for x > 0
	  // atan2(+/-y,+Inf) = +/-0 for finite y>0
	  return copysign (0, y0);
	}
      // now y = +/-Inf
      // atan2(+/-Inf,x) = +/-pi/2 for finite x
      return copysign (PI_OVER2_H, y0) + copysign (PI_OVER2_L, y0);
    }

  if (__glibc_unlikely (aiy == 0 || aix == 0))
    {
      if (aiy == 0 && aix == 0)
	{
	  if (ix == 0) // atan2(+/-0, +0) = +/-0
	    return y0;
	  // atan2(+/-0, +0) = +/-pi
	  return (iy == 0) ? PI_H + PI_L : -PI_H - PI_L;
	}
      // only one of y and x is zero
      if (aiy == 0)
	{
	  // atan2(+/-0,x) = +/-0 for x>0
	  if (x0 > 0)
	    return y0 / x0;
	  // atan2(+/-0,x) = +/-pi for x<0
	  return (!(iy >> 63)) ? PI_H + PI_L : -PI_H - PI_L;
	}
      // now only x is zero
      // atan2(y,+/-0) = -pi/2 for y<0
      // atan2(y,+/-0) = +pi/2 for y>0
      return (y0 > 0) ? PI_OVER2_H + PI_OVER2_L : -PI_OVER2_H - PI_OVER2_L;
    }
  return 0;
}

double
__ieee754_atan2 (double y0, double x0)
{
  static const double asgn[2] = { 0.0, -0.0 };

  uint64_t iy = asuint64 (y0), ix = asuint64 (x0);
  uint64_t aiy = iy & MASK;
  if (__glibc_unlikely (aiy == 0 || aiy >= UINT64_C (0x7ff) << 52))
    return as_atan2_special (y0, x0);
  uint64_t aix = ix & MASK;
  if (__glibc_unlikely (aix == 0 || aix >= UINT64_C (0x7ff) << 52))
    return as_atan2_special (y0, x0);
  double ax = fabs (x0), ay = fabs (y0);
  double x = USE_FMAX_BUILTIN ? fmax (ax, ay) : (ax < ay ? ay : ax);
  double y = USE_FMIN_BUILTIN ? fmin (ax, ay) : (ax < ay ? ax : ay);
  uint64_t sy = iy >> 63, sx = ix >> 63;
  uint64_t GT = aix < aiy;
  uint64_t dxy = (aix - aiy) ^ -GT;
  if (__glibc_unlikely (dxy >= UINT64_C (53) << 52))
    return atan2_accurate (y0, x0);
  double sgn = asgn[GT ^ sx ^ sy];
  uint64_t kw = sx << 2 | sy << 1 | GT;
  uint64_t jj = asuint64 (y / x + (2 + 1 / 128.));
  int64_t jt = ((jj >> (52 - 7)) & 127);
  double fh = f2[jt][1] * copysign (1, sgn);
  double fl = f2[jt][0] * copysign (1, sgn);
  fh += O[kw][0];
  fl += O[kw][1];
  if (__glibc_unlikely (x < 0x1p-968))
    {
      x *= 0x1p968;
      y *= 0x1p968;
    }
  if (__glibc_unlikely (x > 0x1p1022))
    {
      if (__glibc_likely (jt != 0))
	{
	  x *= 0x1p-1;
	  y *= 0x1p-1;
	}
    }
  double t0 = T2[jt];
  double zn = fma (-t0, x, y), zd = fma (t0, y, x);
  double z = zn / zd;
  static const double b[]
      = { -0x1.55555555554d2p-2, 0x1.999999860e1cap-3, -0x1.248ad469844a1p-3 };
  double z2 = z * z;
  z *= copysign (1, sgn);
  double dz = (z * z2) * (b[0] + z2 * (b[1] + z2 * b[2]));
  // this bound is obtained with 1.1e10 random argument pairs in the roundup
  // mode; the obtained maximal difference is increased by 2.5% for safety
  double eps = fabs (z) * 0x1.051p-51 + 0x1p-90;
  double rh = fasttwosum (fh, z, &z);
  double rl = (fl + dz) + z;
  double lb = rh + (rl - eps), ub = rh + (rl + eps);
  if (lb != ub)
    {
      double dh = y * t0, dl = fma (y, t0, -dh), e, rdh;
      dh = fasttwosum (x, dh, &e);
      // avoid spurious underflow in 1/dh
      if (__glibc_likely (fabs (dh) <= 0x1p1022))
	rdh = 1 / dh;
      else
	{
	  fexcept_t flag;
	  __fegetexceptflag (&flag, FE_UNDERFLOW);
	  rdh = 1 / dh;
	  __fesetexceptflag (&flag, FE_UNDERFLOW);
	}
      dl += e;
      double nh = x * t0, nl = fma (x, t0, -nh);
      double dt = y - nh, y1 = dt + nh;
      if (__glibc_likely (y1 == y))
	{
	  nh = fasttwosum (dt, -nl, &nl);
	}
      else
	{
	  nh = fasttwosum (dt, (y - y1) - nl, &nl);
	}
      double zh = nh * rdh;
      z2 = zh * zh;
      double zl = rdh * (fma (dh, -zh, nh) + (nl - (nh * rdh) * dl));
      static const double b2[]
	  = { -0x1.5555555555555p-2, 0x1.999999999755ep-3,
	      -0x1.24924883596f8p-3, 0x1.c6f7d73531bc2p-4 };
      zl += zh * z2
	    * ((b2[0] + z2 * b2[1]) + (z2 * z2) * (b2[2] + z2 * b2[3]));
      zh *= copysign (1, sgn);
      zl *= copysign (1, sgn);
      eps = 0x1.4p-50 * (fabs (zh) * z2 + 0x1p-51);
      fh = fastsum (fh, fl, zh, zl, &fl);
      lb = fh + (fl - eps);
      ub = fh + (fl + eps);
      if (lb != ub)
	return atan2_accurate (y0, x0);
    }
  return ub;
}

#ifndef __ieee754_atan2
libm_alias_finite (__ieee754_atan2, __atan2)
#endif
